# Generated by Django 3.0.2 on 2020-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='connection_error',
            field=models.BooleanField(default=False),
        ),
    ]
